<a href="https://colab.research.google.com/github/agarwal-peeush/MachineLearning/blob/master/Python/Learn/1_Intro_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Import the numpy library
# np is alias, and it is standard, but you can use other alias too
import numpy as np

In [0]:
array_1d = np.array([2,4,5,6,7,9])
print (array_1d)
print (type(array_1d))

[2 4 5 6 7 9]
<class 'numpy.ndarray'>


In [0]:
array_2d = np.array([[2,3,4],[5,8,7]])
print(array_2d)
print(type(array_2d))

[[2 3 4]
 [5 8 7]]
<class 'numpy.ndarray'>


In [0]:
#axes
# axis = 0 => 
# axis = 1 => 

In [0]:
# Difference between list and ndarray
list_1 = [3,6,7,5]
list_2=[4,5,1,7]
# the list way to do it: map a function to the two lists
product_list = list(map(lambda x, y: x*y, list_1, list_2))
print (product_list)

# The numpy array way to do it: simply multiply the two arrays. 
# Size should be equal for both arrays
array_1 = np.array(list_1)
array_2 = np.array(list_2)
array_3 = array_1 * array_2
print (array_3)
print (type(array_3))

[12, 30, 7, 35]
[12 30  7 35]
<class 'numpy.ndarray'>


In [0]:
# Square list vs array
squared_list_1 = [i**2 for i in list_1]
print(squared_list_1)

squared_array_1 = array_1 ** 2
print(squared_array_1)

[9, 36, 49, 25]
[ 9 36 49 25]


In [0]:
array_from_list = np.array([3,4,5,6])
array_from_tuple = np.array((1,2,3,4))
print(array_from_list)
print(array_from_tuple)

[3 4 5 6]
[1 2 3 4]


In [0]:
# NumPy shortcuts to create common arrays as and when required

help(np.ones)

Help on function ones in module numpy.core.numeric:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    zeros, ones_like
    
    Examples
    --------
    >>> np.ones(5)
    array([ 1.,  1.,  1.,  1.,  1.])
    
    >>> np.ones((5,), dtype=int)
    array([1, 1, 1, 1, 1])
    
    >>> np.ones((2, 1))
    array([[ 1.],
           [ 1.]])
    
    >>> s = (2,2)
    >>> np.ones(s)
    ar

In [0]:
# create Identity matrix for 5x3
print(np.ones((5,3)))
print(np.ones((5,3),dtype=np.int))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [0]:
# create array of zeros

np.zeros(4, dtype=np.int)

# create an arry of random numbers
np.random.random([3,4])

numbers = np.arange(10,100, 5)
print (numbers)

np.linspace(15,18,25)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


array([15.   , 15.125, 15.25 , 15.375, 15.5  , 15.625, 15.75 , 15.875,
       16.   , 16.125, 16.25 , 16.375, 16.5  , 16.625, 16.75 , 16.875,
       17.   , 17.125, 17.25 , 17.375, 17.5  , 17.625, 17.75 , 17.875,
       18.   ])

In [0]:
# Initialise an array of random numbers of size 1000x300
rand_array = np.random.random((1000,300))
print(rand_array[0,]) # Print first row

[0.45907528 0.75401805 0.40817842 0.95970927 0.40361463 0.64573745
 0.84261964 0.52355271 0.70750421 0.80982217 0.92609239 0.96864465
 0.35850267 0.05367661 0.91411961 0.4491092  0.9686621  0.08268776
 0.36854355 0.59950053 0.00469936 0.83075136 0.00206565 0.46962513
 0.84846603 0.47479705 0.67235484 0.2057091  0.3638239  0.51395704
 0.08967521 0.66016977 0.77194244 0.82933771 0.19258277 0.8897256
 0.3298637  0.83297026 0.5509336  0.02248607 0.54060487 0.04210925
 0.05133414 0.92791314 0.07679252 0.50626373 0.99304822 0.10083278
 0.08334529 0.81031647 0.80619803 0.92876883 0.0840616  0.39461222
 0.34402243 0.95368426 0.47133754 0.37004544 0.35491683 0.17025317
 0.6707711  0.73496693 0.88992725 0.10706536 0.60854429 0.18253813
 0.4715292  0.66483864 0.52813188 0.65911149 0.81227683 0.16182905
 0.76316495 0.37262047 0.25499378 0.14842032 0.88109824 0.85632956
 0.89925824 0.68366243 0.52549775 0.68996904 0.0813697  0.98139342
 0.96222972 0.43685813 0.89967943 0.98684587 0.28120392 0.83350

In [0]:
# Creating a 3-d array
# np.arange(24) will give numbers from 0 to 23 with step of 1.
# reshape() simply reshapes a 1-D array
array_3d = np.arange(24).reshape(2,3,4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## Subset, Slice, Index and Iterate through Arrays

In [0]:
# Indexing and slicing 1-d array
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
# Third element
print(array_1d[2])

# Specific elements
print(array_1d[[2,5,6]])

# Slice 3rd element onwards
print(array_1d[2:])

# Slice first 3 elements
print(array_1d[:3])

# Slice third to seventh elements
print(array_1d[2:7])

# Subset starting 0 at increment of 2
print(array_1d[0::2])

2
[2 5 6]
[2 3 4 5 6 7 8 9]
[0 1 2]
[2 3 4 5 6]
[0 2 4 6 8]


In [0]:
# Iterate through arrays

for i in array_1d:
  print(i**2)


0
1
4
9
16
25
36
49
64
81


In [0]:
array_2d = np.array([[2,5,7,5],[4,6,8,10],[10,12,15,19]])
print(array_2d)

[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]


In [0]:
print(array_2d[2,1]) # 3rd row 2nd column

# Slicing second row, and all columns
print(array_2d[1,:])
print (type(array_2d[1,:]))

# Slicing all rows and 3rd column
print(array_2d[:,2])

# Slicing all rows and first 3 columns
print(array_2d[:, :3])

# Picking first and 3rd row and all columns
print(array_2d[[0,2],:])

12
[ 4  6  8 10]
<class 'numpy.ndarray'>
[ 7  8 15]
[[ 2  5  7]
 [ 4  6  8]
 [10 12 15]]
[[ 2  5  7  5]
 [10 12 15 19]]


In [0]:
# Iterating over 2-d arrays
for row in array_2d:
  print(row)

[2 5 7 5]
[ 4  6  8 10]
[10 12 15 19]


## Comparison between NumPy arrays and normal Python list

In [0]:
# Comparing time taken for computation
list_1 = [i for i in range(1000000)]
list_2 = [i**2 for i in range(1000000)]

# list multiplication
import time

# store start time, time after computation, and take the difference
t0 = time.time()
product_list = list(map(lambda x,y: x*y, list_1, list_2))
t1 = time.time()
list_time = t1-t0
print (list_time)

# Numpy arrays
array_1 = np.array(list_1)
array_2 = np.array(list_2)

t2 = time.time()
product_array = array_1 * array_2
t3 = time.time()
array_time = t3-t2
print (array_time)

print("The ratio of time taken is {}".format(list_time/array_time))

0.22791552543640137
0.010183095932006836
The ratio of time taken is 22.381751773547798


## Operations on Numpy arrays

In [0]:
array_1 = np.arange(0,12).reshape(3,4)
array_2 = array_1.reshape(2,6)
print(array_1)
print(array_2)

# Define 1 dimension and another one as "-1" and numpy will automatically 
# compute other dimension size
print(array_2.reshape(4,-1)) 

# Transpose of array
print(array_1.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Stacking: Horizontal stack and Vertical stack

In [0]:
array_1 = np.arange(12).reshape(3,4)
array_2 = np.arange(12,32).reshape(5,4)

print(array_1)
print (array_2)

#Vstack : Columns should be same for both arrays
np.vstack((array_1, array_2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [0]:
array_3 = np.arange(12).reshape(4,3)
array_4 = np.arange(12,32).reshape(4,5)

print(array_3)
print(array_4)

#Hstack : Rows should be same
np.hstack((array_3, array_4))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]
 [27 28 29 30 31]]


array([[ 0,  1,  2, 12, 13, 14, 15, 16],
       [ 3,  4,  5, 17, 18, 19, 20, 21],
       [ 6,  7,  8, 22, 23, 24, 25, 26],
       [ 9, 10, 11, 27, 28, 29, 30, 31]])

## User-defined functions on array

In [0]:
# basic functions
array_1 = np.arange(1,13).reshape(3,4)

print(np.sin(array_1))
print(np.cos(array_1))
print(np.exp(array_1))
print(np.log(array_1))

[[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825]
 [ 0.41211849 -0.54402111 -0.99999021 -0.53657292]]
[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225 -0.14550003]
 [-0.91113026 -0.83907153  0.0044257   0.84385396]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]
 [8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05]]
[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]]


In [0]:
array_2 = np.arange(1,20)
print(array_2)

# Not recommended: Non-numpy way to apply user-defined function on array
array_list = [x/(x+1) for x in array_2]
print(array_list)

# Recommended: The numpy way o vectorize function and apply it
fn = np.vectorize(lambda x: x/(x+1))
print(fn(array_2))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.8888888888888888, 0.9, 0.9090909090909091, 0.9166666666666666, 0.9230769230769231, 0.9285714285714286, 0.9333333333333333, 0.9375, 0.9411764705882353, 0.9444444444444444, 0.9473684210526315, 0.95]
[0.5        0.66666667 0.75       0.8        0.83333333 0.85714286
 0.875      0.88888889 0.9        0.90909091 0.91666667 0.92307692
 0.92857143 0.93333333 0.9375     0.94117647 0.94444444 0.94736842
 0.95      ]


## Basic Linear Algebra operations

In [0]:
# np.linalg package

array_1 = np.arange(1,10).reshape(3,3)
array_2 = np.arange(1,13).reshape(3,4)

print(array_1)
print(array_2)

print(np.dot(array_1, array_2))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 38  44  50  56]
 [ 83  98 113 128]
 [128 152 176 200]]


In [0]:
# inverse - NOT WORKING
#np.linalg.inv(array_1)

LinAlgError: ignored

In [0]:
# Determinant value
print(np.linalg.det(array_1))

0.0


In [0]:
# Eigen values and eigen vectors
print(np.linalg.eig(array_1))

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))
